### ISSUE TITLE
`OSError: [Errno 22] Invalid argument` when trying to run `cpuset-modify` on `user.slice`

### ISSUE THREAD

**Issue by nadiamoe** [spheenik/vfio-isolate#16]
Today I noticed that after a system upgrade if I attempt to run `vfio-isolate cpuset-modify --cpus C0-15 user.slice`, it no longer works:

```console
17:02:29 ~ #> vfio-isolate cpuset-modify --cpus C0-15 user.slice
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/vfio-isolate", line 33, in <module>
    sys.exit(load_entry_point('vfio-isolate==0.5.2', 'console_scripts', 'vfio-isolate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cli.py", line 200, in run_cli
    executor.run()
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cli.py", line 191, in run
    for undo in e.action.record_undo(e.params):
  File "/usr/lib/python3.11/site-packages/vfio_isolate/action/cpuset_modify.py", line 39, in record_undo
    cpus=cpu_set.get_cpus(),
         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 69, in get_cpus
    return self.impl.get_cpus(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 232, in get_cpus
    CGroupV2.ensure_cpuset_controller_enabled(cpuset)
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 228, in ensure_cpuset_controller_enabled
    CGroupV2.enable_controller(cpuset, "cpuset")
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 222, in enable_controller
    with cpuset.open("cgroup.subtree_control", "w") as f:
OSError: [Errno 22] Invalid argument
```

Changing the cpuset from `--cpus C0-15` to something else does not seem to make any difference. The command does work for `system.slice`, strangely enough.

I'm running
```
#> uname -a
Linux Archiroo 6.1.53-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 09:32:00 +0000 x86_64 GNU/Linux
```

with `systemd 254.3-1`, in case it is relevant.

**Comment by Ranguvar** [comment]
I saw the same behavior -- failed cpuset.open("cgroup.subtree_control"...
system.slice worked for me also.
I even checked /sys/fs/cgroup/user.slice/cgroup.subtree_control. It exists and appears normal.

I am using kernel 6.5.5-arch1-1 with systemd 254.5-1. Not sure which update caused this or how recently.

vfio-isolate seemed to become intermittent some weeks or even longer ago.
I was noticing silent failures to restore the undo file or give back cores to the host.
I  had no time to look at it or even use it much, but I did just now find the same error message as roobre.

Previously, I was experiencing silent failures to restore the undo file and free cores up to the host again -- after successfully spawning the VM and restricting cores.

The error then disappeared suddenly while I  was adding print statements for logging and testing repeatedly.
I believe even a simple cpuset-modify was failing at one point, and then began working consistently.

I have a feeling this may return on next boot - if it does, I'll try to document what exactly gets around it.
Happy to run any other debugging needed.

**Comment by Ranguvar** [comment]
This is what I'm getting on a fresh boot of 6.5.6-arch2-1

I have the vfio_isolate command-line used below along with a crude debug from this non-Python guy
`/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py` has an extra print:
```
def open(self, file, mode='r'):
        print (self.__path(file))
        return open(self.__path(file), mode)
```
Those are the paths you see printed on their own lines

vfio-isolate -v -u /var/run/libvirt/qemu/vfio-isolate-undo.bin 		drop-caches 		cpuset-modify --cpus C8-14,24-30 /system.slice 		cpuset-modify --cpus C8-14,24-30 /user.slice 		compact-memory 		cpu-governor performance C0-7,15-23,31 		irq-affinity mask C0-7,15-23,31
```
/sys/fs/cgroup/system.slice/cgroup.controllers
/sys/fs/cgroup/system.slice/cgroup.subtree_control
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/vfio-isolate", line 33, in <module>
    sys.exit(load_entry_point('vfio-isolate==0.5.2', 'console_scripts', 'vfio-isolate')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cli.py", line 200, in run_cli
    executor.run()
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cli.py", line 191, in run
    for undo in e.action.record_undo(e.params):
  File "/usr/lib/python3.11/site-packages/vfio_isolate/action/cpuset_modify.py", line 39, in record_undo
    cpus=cpu_set.get_cpus(),
         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 70, in get_cpus
    return self.impl.get_cpus(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 233, in get_cpus
    CGroupV2.ensure_cpuset_controller_enabled(cpuset)
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 229, in ensure_cpuset_controller_enabled
    CGroupV2.enable_controller(cpuset, "cpuset")
  File "/usr/lib/python3.11/site-packages/vfio_isolate/cpuset.py", line 223, in enable_controller
    with cpuset.open("cgroup.subtree_control", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory
taskset -pc 8-14,24-30 2
pid 2's current affinity list: 0-31
```

```
[ranguvar@khufu ~]$ ls -l /sys/fs/cgroup/system.slice/cgroup.subtree_control
-rw-r--r-- 1 root root 0 Oct  7 21:31 /sys/fs/cgroup/system.slice/cgroup.subtree_control
[ranguvar@khufu ~]$ cat /sys/fs/cgroup/system.slice/cgroup.subtree_control
memory pids
</snip>
[ranguvar@khufu ~]$ ls -l /sys/fs/cgroup/user.slice/cgroup.subtree_control
-rw-r--r-- 1 root root 0 Oct  7 22:06 /sys/fs/cgroup/user.slice/cgroup.subtree_control
[ranguvar@khufu ~]$ cat /sys/fs/cgroup/user.slice/cgroup.subtree_control
cpu memory pids
```

Both slices however are not functioning at the moment.
If I try vfio-isolate as a normal user I see lack of permission to open the same file so it clearly sees the file there.
I'm not sure why the FileNotFoundError doesn't show the path it failed on, as it does if I give a bad slice name...

I tried this [old trick](https://unix.stackexchange.com/a/527602) to get system.slice/cgroup.subtree_control to add cpu, since it just seems to once needed, but that didn't help.

UPDATE: I think I got a temporary fix?
Boot the VM and observe that the libvirtd qemu hook's invocations of vfio-isolate continue to fail in the same way.
Then, run a separate vfio-isolate cpuset-modify command, and it succeeds. I did on both /user and /system slices.
cgroup.subtree_control files now contain 'cpuset' too.
Now it is working smoothly, I assume until next boot. 

UPDATE2: Now I'm unable to put a load on cores even when I add them back to /system.slice or /user.slice and see no output from vfio-isolate -v (after VM boots).
